### ISSUE TITLE
Task: Generate PDF from dynContent

### ISSUE THREAD

**Issue by bjoffk** [Bearukun/Polygon#32]

**Comment by radeonxray** [comment]
Initial test of the PDF creator withs he Apache Library:
https://github.com/Bearukun/Polygon/commit/156e6e8201fa206b84439ebdcb892e03b484a208

Basic PDFCreator setup:
https://github.com/Bearukun/Polygon/commit/82fb73c1fd88f7be6bf218bfd5299f27c8b48014

Added a few comments
https://github.com/Bearukun/Polygon/commit/0caf0518844fa32b709a65794fbb38a97562fd00

Basic setup of the layout for the PDF
https://github.com/Bearukun/Polygon/commit/0dd133fe3793bbd37190f7f3b8e4d53658080b3c

Further development of the PDF layout, now includes pictures.
https://github.com/Bearukun/Polygon/commit/85aec5f1014178b991b2f516ca5429481061b205

Page 1 almost complete, initial Page 2 development begun
https://github.com/Bearukun/Polygon/commit/e4505239bbb39a5026efa90c850dfd0acc686db1

Page 2 being worked on, page 3 development underway:
https://github.com/Bearukun/Polygon/commit/40e4e9863259242fe7f3a0042609c4f01bd6a009

Revision to the way that the pdf is saved:
https://github.com/Bearukun/Polygon/commit/677f96e4f60294f76ed079cdfccb396c3cd38f4b

More comments:
https://github.com/Bearukun/Polygon/commit/457af8437ea579819a8ceeb697f6b266e3ced16b

Page 2 layout complete:
https://github.com/Bearukun/Polygon/commit/b4007ee57547c377850124eb33cb5a1ee3b9619a

Beginning of the major revision and setup of the code:
https://github.com/Bearukun/Polygon/commit/041010e7f3347b8947f132f321cad74be609a198
Revision Part 2: https://github.com/Bearukun/Polygon/commit/3ffbe465099ca3a37d42bda47c9dd1333991b989
Revision Part 3:
https://github.com/Bearukun/Polygon/commit/f1555bff8be4d5862be084fd99bd84f0f317df09
Revision Part 4:
https://github.com/Bearukun/Polygon/commit/a274c8c012457ed73b260548c6fd0a4033257a47
Revision Part 5:
https://github.com/Bearukun/Polygon/commit/991afefb868095ddbde5706f3194ec69a8f74109
Revision Part 6:
https://github.com/Bearukun/Polygon/commit/05906d79076d8ba70992c15186bc805c800d2ceb

Major overhaul of the way we handle checkBoxImages:
https://github.com/Bearukun/Polygon/commit/88a8f00fc298fb62b4b1f5dfd4961a7f9c1f6414

Revision of the page3MoistScan method
https://github.com/Bearukun/Polygon/commit/1c26007186f5028664ddd649d50acbbe02bdad12

Basic Page3 layout complete:
https://github.com/Bearukun/Polygon/commit/d7940d86c5c3b941e7bdf2ca13d5210732e2ba48

Basic Page4 layout complete:
https://github.com/Bearukun/Polygon/commit/7b8f9127c0636b82f2e5b107f9183d1b8bbb6701

Visual and basic layout of the PDF complete:
https://github.com/Bearukun/Polygon/commit/73ce86c0058013fc20da8d2acaffb37ac78f3846

LOTS of comments added:
https://github.com/Bearukun/Polygon/commit/e2b4db9d6b10e7b3a789808fa59a09fd4ce23ceb

Revision of 'Gennemgang af lokalet'
https://github.com/Bearukun/Polygon/commit/e13e852cc3d193d777d1c9419b7f4ba29af986bf

Revision to the way that the PDF document is generated, in order to accommodate dynamic content!
https://github.com/Bearukun/Polygon/commit/ebf2bd8566569965654f493a56c4e1ef661a396d

Renaming of methods to reflect the pdf's dynamic flexibility:
https://github.com/Bearukun/Polygon/commit/ad0ccbfcfca9602aad7d6092b0300878539f1715




Linking PDFCreator with the Technician.java, for auto generating data (Page 1 basic done)
https://github.com/Bearukun/Polygon/commit/dd8e09713fdedb949bfae16a301a4fca377dd50d

**Comment by bjoffk** [comment]
Functionality added to tech-Finish healthcheck button, PDF is now generated: 
https://github.com/Bearukun/Polygon/commit/afee09b6e31a707152d84383b960dec31edde40c
